/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrihlasenieRouteImport } from './routes/prihlasenie'
import { Route as RegistraciaRouteImport } from './routes/registracia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlasenieRoute = PrihlasenieRouteImport.update({
  id: '/prihlasenie',
  path: '/prihlasenie',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraciaRoute = RegistraciaRouteImport.update({
  id: '/registracia',
  path: '/registracia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/registracia': typeof RegistraciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/registracia': typeof RegistraciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/registracia': typeof RegistraciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prihlasenie' | '/registracia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prihlasenie' | '/registracia'
  id: '__root__' | '/' | '/prihlasenie' | '/registracia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrihlasenieRoute: typeof PrihlasenieRoute
  RegistraciaRoute: typeof RegistraciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlasenie': {
      id: '/prihlasenie'
      path: '/prihlasenie'
      fullPath: '/prihlasenie'
      preLoaderRoute: typeof PrihlasenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registracia': {
      id: '/registracia'
      path: '/registracia'
      fullPath: '/registracia'
      preLoaderRoute: typeof RegistraciaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrihlasenieRoute: PrihlasenieRoute,
  RegistraciaRoute: RegistraciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
